# Enable the RPM Fusion Free repository:
# https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/
---
- name: Enable the RPM Fusion Free repository
  hosts: fedora
  tasks:
    - name: DNF - Install DNF plugins
      become: true
      dnf:
        state: latest
        name: dnf-plugins-core

    - name: Get Fedora version
      ignore_errors: true
      shell: "rpm -E %fedora"
      register: fedora_version

    - name: DNF - Enable the Free repository
      become: true
      dnf:
        state: latest
        name: "https://download1.rpmfusion.org/free/fedora/\
          rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
